### ISSUE TITLE
osGetSystemVersionData causes file access to fail

### ISSUE THREAD

**Issue by svanheulen** [smealum/ctrulib#246] opened 2016-01-19 00:40 UTC
It appears that after using osGetSystemVersionData I can no longer open files.
Here's some example code that shows the bug: https://gist.github.com/svanheulen/c02033d70f674c2a3169
The first attempt to open the file will succeed (remember to make the "test.txt" file)
Then the second attempt, after osGetSystemVersionData is used, will fail.

**Comment by mtheall** [comment] 2016-01-19 00:51
I can confirm this. errno is set to ENOSYS

**Comment by mtheall** [comment] 2016-01-19 00:53
It appears that sdmc_open() is not being called for the second fopen()

**Comment by mtheall** [comment] 2016-01-19 01:03
After calling osGetSystemVersionData(), FindDevice("sdmc:") returns -1. Is something calling sdmcExit() in libctru?

**Comment by mtheall** [comment] 2016-01-19 01:22
I can confirm that before osGetSystemVersionData(), the devoptab_list[] has the following contents:
devoptab_list[1] -> con
devoptab_list[2] -> con
devoptab_list[3] -> sdmc

After osGetSystemVersionData(), the devoptab_list[] has the following contents:
devoptab_list[1] -> con
devoptab_list[2] -> con
devoptab_list[3] -> dotab_stdnull
devoptab_list[4] -> romfs

**Comment by mtheall** [comment] 2016-01-19 01:29
osGetSystemVersionData() calls __read_versionbin()
__read_versionbin() calls romfsInitFromFile()/romfsExit()
but after romfsExit() the sdmc dev is gone but romfs dev is still there. problem in newlib or libctru?

**Comment by svanheulen** [comment] 2016-01-19 01:32
I noticed in __read_versionbin() it calls FSUSER_OpenFileDirectly but never calls FSFILE_Close on that handle. Could that be an issue?

**Comment by mtheall** [comment] 2016-01-19 01:34
Fixed with 07f0fe7e6

**Closed by mtheall** 2016-01-19 01:34 UTC

**Comment by mtheall** [comment] 2016-01-19 01:36
It probably is a bug that the file handle isn't closed, but that wasn't the cause of this issue.

**Comment by Lectem** [comment] 2016-01-19 01:38
> I noticed in __read_versionbin() it calls FSUSER_OpenFileDirectly but never calls FSFILE_Close on that handle. Could that be an issue?

Nope, the file is cleared by romfsExit() here https://github.com/smealum/ctrulib/blob/master/libctru/source/romfs_dev.c#L228

**Comment by svanheulen** [comment] 2016-01-19 01:41
Awesome! Thanks for fixing that so fast!

**Comment by mtheall** [comment] 2016-01-19 01:54
No problem, I'm glad it wasn't something harder to debug.
