### ISSUE TITLE
extend the Parx-GDI :: C lib with Parx-Pas :: FreePascal stubs & templates!

### ISSUE THREAD

**Issue by kennyd-lee** [smealum/ctrulib#270] opened 2016-03-22 22:24 UTC
I wrote "Athabasca U" were I was enrolled with,
# quote
(Please with out your "lovely" documentation & or further financial support. I fear your 3DS device will fall to no less than Marxist/Leninist/Nintendo pertain only to "VideoGame;by proxy; dictatorships")

& U half bin found under the influence of FPC, in politics of 3DS to a Computer science? U will be processed @ the academic inbreeding facilities immediately  
--->  http://free-pascal-lazarus.989080.n3.nabble.com/I-ve-got-a-quot-nintendo-3ds-pascal-quot-that-can-all-day-tc4041255.html
# quote end

Co. Github :: 
"Three-DS" :: "Parx-3DS" :: "Radio-Freedom" gnu c/c+ & "FPC-2.2.2", FreePascal & the "ctru-pas" 

who is it i ask to append 
"extend the Parx-GDI :: C lib with Parx-Pas :: FreePascal stubs & templates!" >> https://www.3dbrew.org/wiki/Homebrew_Libraries_and_Tools

brief & Info:
FPC / FreePascal 3ds development testbed & bench sales & Info Contact: 
[linkedin](https://ca.linkedin.com/in/kennyd-lee-b6bb92b4), [Parx](https://www.facebook.com/Parx-1735214770048259), [twitter](https://twitter.com/Kenny_D_Lee) & the [n3ds-freepascal](https://www.facebook.com/n3ds-freepascal-1596037147331761)  
Via Phone: 1-819-205-2321
Co. Kenneth Dwayne Lee
78 "A" Rue. Garneau, Gatineau Qc. J8X-1S2 Canada 

& last anyone email "Athabasca U" so I "Kenneth Dwayne Lee :: Dob. Jan 10 1972" may obtain rendering from their "Approval Program" of the alumni & or computer science faculty  >>  fst_success@athabascau.ca

**Comment by profi200** [comment] 2016-03-22 22:35
# WTF

(sorry i had to)

**Comment by Cruel** [comment] 2016-03-22 22:39
LGTM

**Comment by Steveice10** [comment] 2016-04-10 21:01
Probably can be closed?

**Comment by smealum** [comment] 2016-04-10 22:28
after careful deliberation we've decided that this is by design so we won't fix it.

thanks for reporting

**Closed by smealum** 2016-04-10 22:28 UTC
