### ISSUE TITLE
Input not working

### ISSUE THREAD

**Issue by neobrain** [smealum/ctrulib#195] opened 2015-10-20 15:54 UTC
Building FTP-3DS with recent ctrulib versions yields a application which lacks input support. In particular, FTP-3DS doesn't detect any button presses, but still works fine other than that. From quick testing it seems this also affects (all?) other applications.

It was suggested on IRC that this is a regression from 9fe9493701a0ae86adc3f56d6d1cd318a5875d70 . I did not specifically confirm this, but I can tell that c765e3b559f1b38012e3fd4e98d3d450f64aba3d does not have the issue.

**Comment by thedax** [comment] 2015-10-20 21:52
I personally can't reproduce this, I'm on the latest commit of the master branch (https://github.com/smealum/ctrulib/commit/e12c8ff6a6690928e02e3696d1d32009a5d5abd4) and the samples, plus my own random assortment of programmed homebrews work fine. I'll try grabbing the source for FTP-3DS to see.

**Comment by Steveice10** [comment] 2015-10-20 23:12
Worked fine for me when I tested that change.

**Comment by thedax** [comment] 2015-10-20 23:47
FTP-3DS also works fine for me, when compiled with e12c8ff.

**Comment by neobrain** [comment] 2015-10-20 23:53
Fwiw people on #3dsdev suggested that the problem only shows up sporadically for them. Either way, I'll double check when I get some time (might take me a few days) if I can reproduce the issue (since for now I've downgraded to an older ctrulib version).

**Comment by smealum** [comment] 2015-10-21 06:04
i think i just ran into the same bug.

i pushed a fix : https://github.com/smealum/ctrulib/commit/bba6b90ba006dd2a06df76bb5aeb2ffeeb61163c
it definitely fixes my version of the bug. can you make sure it fixes it for you too @neobrain ?

thanks !

**Comment by neobrain** [comment] 2015-10-21 17:34
Got a chance to test it today, and indeed input is working in great_refactor with that fix (i.e. 89fc70f076222691a604aba7d2cae05254e413d1 ). Haven't tested on master, but since it's working for @smealum I'll just assume it works there too.

Thanks ;)

**Comment by smealum** [comment] 2015-10-21 17:35
woohoo.

**Closed by smealum** 2015-10-21 17:35 UTC
